### ISSUE TITLE
Cropper should allow for no ratios

### ISSUE THREAD

**Issue by simonwinter** [salted-herring/salted-cropper#1]
Currently when using the cropper field you have to specify a ratio like so:

`SaltedUploader::create('Image', 'Image')->setCropperRatio(100/50)`

There are times when the ratio is irrelevant - i.e. you want the user to just use the toll to crop the image to whatever shape they like. Currently it falls back to a 1:1 ratio - I'd like to be able to have an unrestricted cropper if I don't supply a ratio.

**Comment by simonwinter** [comment]
It appears you can fudge this - e.g.:

`SaltedUploader::create('Image', 'Image')->setCropperRatio('NaN')`

will give you an unrestricted box, but would still rather this be the default when you initialise the field:

`SaltedUploader::create('Image', 'Image')`

**Comment by simonwinter** [comment]
@leochenftw Do you know if this is still an issue or can we close this?

**Comment by leochenftw** [comment]
Hi @simonwinter yes, it's already been resolved,. So if you don't set any ratio (or set it to null), it will give you a free cropper box. We can close this issue
